export default interface IPostLow {
    userId: string,
    userImg: string,
    hash: string,
    userName: string,
    userDesc: string,
    postId: string,
    postDate: string,
    postTitle: string,
    postDesc: string,
    postState: boolean,
    postLikeCount: number,
    postCommentCount: number,
    postReplyCount: number,
    postTags: Array<string>,
}